# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design\main_v4.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1265, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_6.addWidget(self.label_24)
        self.cmbCurCipher = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cmbCurCipher.setFont(font)
        self.cmbCurCipher.setObjectName("cmbCurCipher")
        self.horizontalLayout_6.addWidget(self.cmbCurCipher)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.leSourcePath = QtWidgets.QLineEdit(self.centralwidget)
        self.leSourcePath.setObjectName("leSourcePath")
        self.verticalLayout_2.addWidget(self.leSourcePath)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSetSource = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetSource.setObjectName("btnSetSource")
        self.horizontalLayout.addWidget(self.btnSetSource)
        self.btnLoadSource = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadSource.setObjectName("btnLoadSource")
        self.horizontalLayout.addWidget(self.btnLoadSource)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.ptInputText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ptInputText.setObjectName("ptInputText")
        self.verticalLayout_2.addWidget(self.ptInputText)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.leOutPath = QtWidgets.QLineEdit(self.centralwidget)
        self.leOutPath.setObjectName("leOutPath")
        self.verticalLayout_3.addWidget(self.leOutPath)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSetOut = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetOut.setObjectName("btnSetOut")
        self.horizontalLayout_4.addWidget(self.btnSetOut)
        self.btnSaveSource = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveSource.setObjectName("btnSaveSource")
        self.horizontalLayout_4.addWidget(self.btnSaveSource)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.ptOutText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ptOutText.setObjectName("ptOutText")
        self.verticalLayout_3.addWidget(self.ptOutText)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 3, 2, 1)
        self.gbSettings = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gbSettings.setFont(font)
        self.gbSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.gbSettings.setObjectName("gbSettings")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbSettings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tbSettings = QtWidgets.QToolBox(self.gbSettings)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tbSettings.setFont(font)
        self.tbSettings.setObjectName("tbSettings")
        self.pageAlphabet = QtWidgets.QWidget()
        self.pageAlphabet.setGeometry(QtCore.QRect(0, 0, 436, 481))
        self.pageAlphabet.setObjectName("pageAlphabet")
        self.formLayout = QtWidgets.QFormLayout(self.pageAlphabet)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.pageAlphabet)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sbAbcLength = QtWidgets.QSpinBox(self.pageAlphabet)
        self.sbAbcLength.setMinimum(1)
        self.sbAbcLength.setMaximum(2999)
        self.sbAbcLength.setObjectName("sbAbcLength")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbAbcLength)
        self.label_2 = QtWidgets.QLabel(self.pageAlphabet)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.leAbcFL = QtWidgets.QLineEdit(self.pageAlphabet)
        self.leAbcFL.setMaxLength(1)
        self.leAbcFL.setObjectName("leAbcFL")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leAbcFL)
        self.label_3 = QtWidgets.QLabel(self.pageAlphabet)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.leAbcFU = QtWidgets.QLineEdit(self.pageAlphabet)
        self.leAbcFU.setMaxLength(1)
        self.leAbcFU.setObjectName("leAbcFU")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leAbcFU)
        self.label_6 = QtWidgets.QLabel(self.pageAlphabet)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leAbcSourcePath = QtWidgets.QLineEdit(self.pageAlphabet)
        self.leAbcSourcePath.setObjectName("leAbcSourcePath")
        self.horizontalLayout_2.addWidget(self.leAbcSourcePath)
        self.btnAbcLoadSource = QtWidgets.QPushButton(self.pageAlphabet)
        self.btnAbcLoadSource.setObjectName("btnAbcLoadSource")
        self.horizontalLayout_2.addWidget(self.btnAbcLoadSource)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(self.pageAlphabet)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dsbAbcFrequency = QtWidgets.QDoubleSpinBox(self.pageAlphabet)
        self.dsbAbcFrequency.setDecimals(5)
        self.dsbAbcFrequency.setMaximum(1.0)
        self.dsbAbcFrequency.setObjectName("dsbAbcFrequency")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.dsbAbcFrequency)
        self.label_5 = QtWidgets.QLabel(self.pageAlphabet)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.tvAbcLettersFreqs = QtWidgets.QTableWidget(self.pageAlphabet)
        self.tvAbcLettersFreqs.setObjectName("tvAbcLettersFreqs")
        self.tvAbcLettersFreqs.setColumnCount(0)
        self.tvAbcLettersFreqs.setRowCount(0)
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.tvAbcLettersFreqs)
        self.label_26 = QtWidgets.QLabel(self.pageAlphabet)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.pageAlphabet)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_27 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_7.addWidget(self.label_27)
        self.sbFreqKeyFrom = QtWidgets.QSpinBox(self.horizontalGroupBox_2)
        self.sbFreqKeyFrom.setObjectName("sbFreqKeyFrom")
        self.horizontalLayout_7.addWidget(self.sbFreqKeyFrom)
        self.label_28 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_7.addWidget(self.label_28)
        self.sbFreqKeyTo = QtWidgets.QSpinBox(self.horizontalGroupBox_2)
        self.sbFreqKeyTo.setObjectName("sbFreqKeyTo")
        self.horizontalLayout_7.addWidget(self.sbFreqKeyTo)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.horizontalGroupBox_2)
        self.label_25 = QtWidgets.QLabel(self.pageAlphabet)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_25)
        self.tbSettings.addItem(self.pageAlphabet, "")
        self.pageCaesar = QtWidgets.QWidget()
        self.pageCaesar.setGeometry(QtCore.QRect(0, 0, 398, 448))
        self.pageCaesar.setObjectName("pageCaesar")
        self.formLayout_2 = QtWidgets.QFormLayout(self.pageCaesar)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.pageCaesar)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.sbCaesarKey = QtWidgets.QSpinBox(self.pageCaesar)
        self.sbCaesarKey.setObjectName("sbCaesarKey")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbCaesarKey)
        self.tbSettings.addItem(self.pageCaesar, "")
        self.pageAffine = QtWidgets.QWidget()
        self.pageAffine.setGeometry(QtCore.QRect(0, 0, 398, 448))
        self.pageAffine.setObjectName("pageAffine")
        self.formLayout_3 = QtWidgets.QFormLayout(self.pageAffine)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.pageAffine)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.sbAffineB = QtWidgets.QSpinBox(self.pageAffine)
        self.sbAffineB.setObjectName("sbAffineB")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sbAffineB)
        self.sbAffineA = QtWidgets.QSpinBox(self.pageAffine)
        self.sbAffineA.setObjectName("sbAffineA")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbAffineA)
        self.label_9 = QtWidgets.QLabel(self.pageAffine)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.pageAffine)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.sbAffine_A = QtWidgets.QSpinBox(self.pageAffine)
        self.sbAffine_A.setObjectName("sbAffine_A")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sbAffine_A)
        self.tbSettings.addItem(self.pageAffine, "")
        self.pageViginer = QtWidgets.QWidget()
        self.pageViginer.setGeometry(QtCore.QRect(0, 0, 398, 448))
        self.pageViginer.setObjectName("pageViginer")
        self.formLayout_4 = QtWidgets.QFormLayout(self.pageViginer)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtWidgets.QLabel(self.pageViginer)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.leViginerKey = QtWidgets.QLineEdit(self.pageViginer)
        self.leViginerKey.setObjectName("leViginerKey")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leViginerKey)
        self.tbSettings.addItem(self.pageViginer, "")
        self.pageGamma = QtWidgets.QWidget()
        self.pageGamma.setGeometry(QtCore.QRect(0, 0, 398, 448))
        self.pageGamma.setObjectName("pageGamma")
        self.formLayout_5 = QtWidgets.QFormLayout(self.pageGamma)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_12 = QtWidgets.QLabel(self.pageGamma)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.sbGammaInitKey = QtWidgets.QSpinBox(self.pageGamma)
        self.sbGammaInitKey.setMaximum(99999)
        self.sbGammaInitKey.setObjectName("sbGammaInitKey")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sbGammaInitKey)
        self.sbGammaA = QtWidgets.QSpinBox(self.pageGamma)
        self.sbGammaA.setMaximum(99999)
        self.sbGammaA.setObjectName("sbGammaA")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbGammaA)
        self.sbGammaB = QtWidgets.QSpinBox(self.pageGamma)
        self.sbGammaB.setMaximum(99999)
        self.sbGammaB.setObjectName("sbGammaB")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sbGammaB)
        self.label_14 = QtWidgets.QLabel(self.pageGamma)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_13 = QtWidgets.QLabel(self.pageGamma)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.sbGammaM = QtWidgets.QSpinBox(self.pageGamma)
        self.sbGammaM.setMaximum(99999)
        self.sbGammaM.setObjectName("sbGammaM")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sbGammaM)
        self.label_15 = QtWidgets.QLabel(self.pageGamma)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.tbSettings.addItem(self.pageGamma, "")
        self.pageFeistel = QtWidgets.QWidget()
        self.pageFeistel.setGeometry(QtCore.QRect(0, 0, 461, 448))
        self.pageFeistel.setObjectName("pageFeistel")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageFeistel)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sbFeistelA = QtWidgets.QSpinBox(self.pageFeistel)
        self.sbFeistelA.setMaximum(99999)
        self.sbFeistelA.setObjectName("sbFeistelA")
        self.gridLayout_2.addWidget(self.sbFeistelA, 5, 1, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.pageFeistel)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 6, 0, 1, 1)
        self.leFeistelEmptyChar = QtWidgets.QLineEdit(self.pageFeistel)
        self.leFeistelEmptyChar.setMaxLength(1)
        self.leFeistelEmptyChar.setObjectName("leFeistelEmptyChar")
        self.gridLayout_2.addWidget(self.leFeistelEmptyChar, 1, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.pageFeistel)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.pageFeistel)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 8, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.pageFeistel)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 2)
        self.sbFeistelInitKey = QtWidgets.QSpinBox(self.pageFeistel)
        self.sbFeistelInitKey.setMaximum(99999)
        self.sbFeistelInitKey.setObjectName("sbFeistelInitKey")
        self.gridLayout_2.addWidget(self.sbFeistelInitKey, 8, 1, 1, 2)
        self.sbFeistelBlockSize = QtWidgets.QSpinBox(self.pageFeistel)
        self.sbFeistelBlockSize.setMinimum(2)
        self.sbFeistelBlockSize.setMaximum(1024)
        self.sbFeistelBlockSize.setSingleStep(2)
        self.sbFeistelBlockSize.setObjectName("sbFeistelBlockSize")
        self.gridLayout_2.addWidget(self.sbFeistelBlockSize, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.pageFeistel)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.pageFeistel)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.sbFeistelB = QtWidgets.QSpinBox(self.pageFeistel)
        self.sbFeistelB.setMaximum(99999)
        self.sbFeistelB.setObjectName("sbFeistelB")
        self.gridLayout_2.addWidget(self.sbFeistelB, 6, 1, 1, 2)
        self.sbFeistelM = QtWidgets.QSpinBox(self.pageFeistel)
        self.sbFeistelM.setMaximum(99999)
        self.sbFeistelM.setObjectName("sbFeistelM")
        self.gridLayout_2.addWidget(self.sbFeistelM, 7, 1, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.pageFeistel)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 2)
        self.sbFeistelRounds = QtWidgets.QSpinBox(self.pageFeistel)
        self.sbFeistelRounds.setMinimum(1)
        self.sbFeistelRounds.setMaximum(1024)
        self.sbFeistelRounds.setSingleStep(1)
        self.sbFeistelRounds.setObjectName("sbFeistelRounds")
        self.gridLayout_2.addWidget(self.sbFeistelRounds, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.pageFeistel)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 0, 1, 3)
        self.tbSettings.addItem(self.pageFeistel, "")
        self.verticalLayout_4.addWidget(self.tbSettings)
        self.gridLayout.addWidget(self.gbSettings, 1, 0, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 579, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cbClearText = QtWidgets.QCheckBox(self.centralwidget)
        self.cbClearText.setObjectName("cbClearText")
        self.horizontalLayout_8.addWidget(self.cbClearText)
        self.btnCiphering = QtWidgets.QPushButton(self.centralwidget)
        self.btnCiphering.setObjectName("btnCiphering")
        self.horizontalLayout_8.addWidget(self.btnCiphering)
        self.btnSwap = QtWidgets.QPushButton(self.centralwidget)
        self.btnSwap.setObjectName("btnSwap")
        self.horizontalLayout_8.addWidget(self.btnSwap)
        self.btnDeciphering = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeciphering.setObjectName("btnDeciphering")
        self.horizontalLayout_8.addWidget(self.btnDeciphering)
        self.btnFreqAnalysis = QtWidgets.QPushButton(self.centralwidget)
        self.btnFreqAnalysis.setObjectName("btnFreqAnalysis")
        self.horizontalLayout_8.addWidget(self.btnFreqAnalysis)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1265, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tbSettings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.sbAbcLength, self.leAbcFL)
        MainWindow.setTabOrder(self.leAbcFL, self.leAbcFU)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "РГР Защита информации"))
        self.label_24.setText(_translate("MainWindow", "Текущий шифратор"))
        self.btnSetSource.setText(_translate("MainWindow", "Обзор"))
        self.btnLoadSource.setText(_translate("MainWindow", "Загрузить"))
        self.btnSetOut.setText(_translate("MainWindow", "Обзор"))
        self.btnSaveSource.setText(_translate("MainWindow", "Сохранить"))
        self.gbSettings.setTitle(_translate("MainWindow", "Настройки"))
        self.label.setText(_translate("MainWindow", "Мощность:"))
        self.label_2.setText(_translate("MainWindow", "Первая прописная:"))
        self.label_3.setText(_translate("MainWindow", "Первая заглавная:"))
        self.label_6.setText(_translate("MainWindow", "Автоподсчет:"))
        self.btnAbcLoadSource.setText(_translate("MainWindow", "Выбрать образец"))
        self.label_4.setText(_translate("MainWindow", "Индекс совападений:"))
        self.label_5.setText(_translate("MainWindow", "Частоты букв:"))
        self.label_26.setText(_translate("MainWindow", "Длина ключа:"))
        self.label_27.setText(_translate("MainWindow", "От:"))
        self.label_28.setText(_translate("MainWindow", "До:"))
        self.label_25.setText(_translate("MainWindow", "Настройки частотного анализа"))
        self.tbSettings.setItemText(self.tbSettings.indexOf(self.pageAlphabet),
                                    _translate("MainWindow", "Алфавит и частотный анализ"))
        self.label_7.setText(_translate("MainWindow", "Ключ:"))
        self.tbSettings.setItemText(self.tbSettings.indexOf(self.pageCaesar), _translate("MainWindow", "Шифр цезаря"))
        self.label_8.setText(_translate("MainWindow", "B:"))
        self.label_9.setText(_translate("MainWindow", "A:"))
        self.label_10.setText(_translate("MainWindow", "-A:"))
        self.tbSettings.setItemText(self.tbSettings.indexOf(self.pageAffine), _translate("MainWindow", "Афинный шифр"))
        self.label_11.setText(_translate("MainWindow", "Ключ:"))
        self.tbSettings.setItemText(self.tbSettings.indexOf(self.pageViginer),
                                    _translate("MainWindow", "Шифр Вижинера"))
        self.label_12.setText(_translate("MainWindow", "Нач. ключ:"))
        self.label_14.setText(_translate("MainWindow", "B:"))
        self.label_13.setText(_translate("MainWindow", "A:"))
        self.label_15.setText(_translate("MainWindow", "M:"))
        self.tbSettings.setItemText(self.tbSettings.indexOf(self.pageGamma), _translate("MainWindow", "Гамма шифр"))
        self.label_22.setText(_translate("MainWindow", "B:"))
        self.label_23.setText(_translate("MainWindow", "M:"))
        self.label_21.setText(_translate("MainWindow", "Нач. ключ:"))
        self.label_17.setText(_translate("MainWindow", "Дополняющий символ:"))
        self.label_20.setText(_translate("MainWindow", "A:"))
        self.label_16.setText(_translate("MainWindow", "Размер блока:"))
        self.label_18.setText(_translate("MainWindow", "Раундов шифрования:"))
        self.label_19.setText(_translate("MainWindow",
                                         "<html><head/><body><p>В качестве функции шифрования используется</p><p>Гамма шифр, настройте его</p></body></html>"))
        self.tbSettings.setItemText(self.tbSettings.indexOf(self.pageFeistel),
                                    _translate("MainWindow", "Блочное шифрование Фейстеля"))
        self.cbClearText.setText(_translate("MainWindow", "Очищать при\n"
                                                          "шифровании и\n"
                                                          "дешифровании"))
        self.btnCiphering.setText(_translate("MainWindow", "Зашифровать >>"))
        self.btnSwap.setText(_translate("MainWindow", ">> Поменять <<"))
        self.btnDeciphering.setText(_translate("MainWindow", "<< Расшифровать"))
        self.btnFreqAnalysis.setText(_translate("MainWindow", "<< Частотный\n"
                                                              "<< анализ"))
